// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umat.Osass.PostgresDb.Sdk.ApplicationContexts;

#nullable disable

namespace Umat.Osass.PostgresDb.Sdk.Migrations.Academic
{
    [DbContext(typeof(AcademicPromotionDbContext))]
    [Migration("20260222144030_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.AcademicPromotionApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantCurrentPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantDepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantDepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFacultyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PerformanceCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PromotionPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatusHistory")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AcademicPromotionApplications");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.AcademicPromotionCommittee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("CanSubmitReviewedApplication")
                        .HasColumnType("boolean");

                    b.Property<string>("CommitteeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text");

                    b.Property<string>("FacultyId")
                        .HasColumnType("text");

                    b.Property<bool>("IsChairperson")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolId")
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AcademicPromotionCommittees");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.AcademicPromotionPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumNumberOfPublications")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumNumberOfRefereedJournal")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumNumberOfYearsFromLastPromotion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformanceCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousPosition")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AcademicPromotionPositions");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.Publication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantDepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.ServiceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantDepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceToNationalAndInternational")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceToTheUniversity")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.AcademicPromotion.TeachingRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AbilityToAdaptToTeaching")
                        .HasColumnType("jsonb");

                    b.Property<string>("AbilityToCompleteSyllabus")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApplicantDepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LectureLoad")
                        .HasColumnType("jsonb");

                    b.Property<string>("PerformanceOfStudentInExam")
                        .HasColumnType("jsonb");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PunctualityInSettingExamQuestion")
                        .HasColumnType("jsonb");

                    b.Property<string>("QualityOfExamQuestionAndMarkingScheme")
                        .HasColumnType("jsonb");

                    b.Property<string>("QualityOfLectureMaterial")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegularityAndPunctuality")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentReactionToAndAssessmentOfTeaching")
                        .HasColumnType("jsonb");

                    b.Property<string>("SupervisionOfProjectWorkAndThesis")
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalCategoriesAssessed")
                        .HasColumnType("integer");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeachingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
