// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umat.Osass.PostgresDb.Sdk.ApplicationContexts;

#nullable disable

namespace Umat.Osass.PostgresDb.Sdk.Migrations.NonAcademic
{
    [DbContext(typeof(NonAcademicPromotionDbContext))]
    [Migration("20260430170815_AddApplicationDocuments")]
    partial class AddApplicationDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.KnowledgeProfessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AapscPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromotionApplicationId")
                        .HasDatabaseName("idx_na_knowledge_application_id");

                    b.HasIndex("ApplicantId", "PromotionApplicationId")
                        .HasDatabaseName("idx_na_knowledge_applicant_application");

                    b.HasIndex("ApplicantId", "Status")
                        .HasDatabaseName("idx_na_knowledge_applicant_status");

                    b.ToTable("KnowledgeProfessionRecords");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.NonAcademicAssessmentActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActivityData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryAffected")
                        .HasColumnType("text");

                    b.Property<string>("CommitteeLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<bool>("PerformedByIsChairperson")
                        .HasColumnType("boolean");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedByStaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("idx_na_activity_applicant_id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_na_activity_application_id");

                    b.HasIndex("ApplicationId", "ActivityType")
                        .HasDatabaseName("idx_na_activity_app_type");

                    b.HasIndex("ApplicationId", "CommitteeLevel", "ActivityType")
                        .HasDatabaseName("idx_na_activity_app_committee_type");

                    b.ToTable("NonAcademicAssessmentActivities");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.NonAcademicPromotionApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantCurrentPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationLetterFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApplicationLetterUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurriculumVitaeFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CurriculumVitaeUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PerformanceCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PromotionPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatusHistory")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("idx_na_application_applicant_id");

                    b.HasIndex("ApplicantUnitId")
                        .HasDatabaseName("idx_na_application_unit_id");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("idx_na_application_review_status_single");

                    b.HasIndex("SubmissionDate")
                        .HasDatabaseName("idx_na_application_submission_date");

                    b.HasIndex("ApplicantId", "IsActive")
                        .HasDatabaseName("idx_na_application_applicant_active");

                    b.HasIndex("ReviewStatus", "ApplicationStatus")
                        .HasDatabaseName("idx_na_application_review_status");

                    b.ToTable("NonAcademicPromotionApplications");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.NonAcademicPromotionCommittee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("CanSubmitReviewedApplication")
                        .HasColumnType("boolean");

                    b.Property<string>("CommitteeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChairperson")
                        .HasColumnType("boolean");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeType")
                        .HasDatabaseName("idx_na_committee_type");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("idx_na_committee_staff_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("idx_na_committee_unit_id");

                    b.HasIndex("StaffId", "CommitteeType")
                        .HasDatabaseName("idx_na_committee_staff_type");

                    b.HasIndex("StaffId", "IsChairperson")
                        .HasDatabaseName("idx_na_committee_staff_chairperson");

                    b.ToTable("NonAcademicPromotionCommittees");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.NonAcademicPromotionPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumNumberOfJournals")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumNumberOfKnowledgeMaterials")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumNumberOfYearsFromLastPromotion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformanceCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousPosition")
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NonAcademicPromotionPositions");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.NonAcademicServiceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AapscPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceToNationalAndInternational")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceToTheUniversity")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromotionApplicationId")
                        .HasDatabaseName("idx_na_service_application_id");

                    b.HasIndex("ApplicantId", "PromotionApplicationId")
                        .HasDatabaseName("idx_na_service_applicant_application");

                    b.HasIndex("ApplicantId", "Status")
                        .HasDatabaseName("idx_na_service_applicant_status");

                    b.ToTable("NonAcademicServiceRecords");
                });

            modelBuilder.Entity("Umat.Osass.PostgresDb.Sdk.Entities.NonAcademicPromotion.PerformanceAtWorkRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AapscPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AbilityToInspireAndMotivate")
                        .HasColumnType("jsonb");

                    b.Property<string>("AbilityToWorkOnOwn")
                        .HasColumnType("jsonb");

                    b.Property<string>("AbilityToWorkUnderPressure")
                        .HasColumnType("jsonb");

                    b.Property<string>("AccuracyOnSchedule")
                        .HasColumnType("jsonb");

                    b.Property<string>("AdditionalResponsibility")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HumanRelations")
                        .HasColumnType("jsonb");

                    b.Property<string>("InitiativeAndForesight")
                        .HasColumnType("jsonb");

                    b.Property<string>("KnowledgeOfProcedures")
                        .HasColumnType("jsonb");

                    b.Property<string>("PromotionApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PunctualityAndRegularity")
                        .HasColumnType("jsonb");

                    b.Property<string>("QualityOfWork")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCategoriesAssessed")
                        .HasColumnType("integer");

                    b.Property<string>("UapcPerformance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromotionApplicationId")
                        .HasDatabaseName("idx_na_work_application_id");

                    b.HasIndex("ApplicantId", "PromotionApplicationId")
                        .HasDatabaseName("idx_na_work_applicant_application");

                    b.HasIndex("ApplicantId", "Status")
                        .HasDatabaseName("idx_na_work_applicant_status");

                    b.ToTable("PerformanceAtWorkRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
